name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install Dependencies
      run: yarn install
    - name: Test
      run: yarn test --forceExit
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
    - name: Upload to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
        SINGLE_COMMIT: true
        GIT_CONFIG_NAME: GitHub Actions
        GIT_CONFIG_EMAIL: gh-actions@example.com
